# bfl_asic/ml/publish.py
"""Optional: push a run directory to the HF Hub as a shareable lab notebook.

huggingface_hub is imported lazily; it lives in the [ml] extra.
"""
from __future__ import annotations

from pathlib import Path


def build_model_card(snapshot) -> str:
    """Render a Markdown model card from an MLSnapshot."""
    lines = [
        "# BFL-ASIC ML Learnability Run",
        "",
        f"- Experiment: **{snapshot.experiment}**",
        f"- Model: `{snapshot.model}`",
        f"- Feature: `{snapshot.feature}`",
        f"- Timestamp: {snapshot.timestamp}",
        "",
        "## Learnability points",
        "",
        "| knob | accuracy | advantage |",
        "|-----:|---------:|----------:|",
    ]
    for p in snapshot.points:
        lines.append(
            f"| {p.get('rounds', '-')} "
            f"| {p.get('accuracy', float('nan')):.4f} "
            f"| {p.get('advantage', float('nan')):.4f} |"
        )
    if snapshot.bounded_null:
        lines += [
            "",
            "## Bounded null",
            "",
            f"> {snapshot.bounded_null.get('conclusion', '')}",
        ]
    lines += [
        "",
        "_Generated by `bfl-asic ml publish`. Datasets are regenerable "
        "from the run seed; none are hosted here._",
    ]
    return "\n".join(lines)


def publish_run(run_dir: Path, repo_id: str, *, private: bool = True) -> str:
    """Write README.md (the generated model card) into *run_dir*, then
    upload the whole directory to the HF Hub. Returns the repo_id.

    Note: this mutates *run_dir* by adding README.md before upload.
    """
    from huggingface_hub import HfApi

    from bfl_asic.ml.snapshot import MLSnapshot

    run_dir = Path(run_dir)
    snap_path = run_dir / "snapshot.json"
    if snap_path.exists() and snap_path.read_text().strip() not in ("", "{}"):
        card = build_model_card(MLSnapshot.load(snap_path))
        (run_dir / "README.md").write_text(card)

    api = HfApi()
    api.create_repo(repo_id, exist_ok=True, repo_type="model", private=private)
    api.upload_folder(repo_id=repo_id, folder_path=str(run_dir))
    return repo_id
